dependencies:
  - base >= 4.14 && < 5
  - HUnit

library:
  source-dirs: src

executables:
  main:
    main: Main.hs
    source-dirs: src

tests:
  test-suite:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - base
      - HUnit
