name: haskellStage9
version: 0.1.0.0
dependencies:
  - base >= 4.7 && < 5
library:
  source-dirs: src
  exposed-modules:
    - QTree
    - Ticket
    - TicketRegistry
executables:
  haskellStage9:
    main: Main.hs
    source-dirs: src
